#Create Service to connect to intranet ic-wep app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ic-web
    environment: production
  name: ic-web-frontend
  namespace: icgroup
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31000
  selector:
    app: ic-web
  type: NodePort