---
  - name: "Creation du dossier odoo"
    file:
      path: /home/{{ ansible_user }}/odoo
      state: directory
      mode: '0755'
  
  - name: "Copie du docker compose"
    template:
      src: "docker-compose.yml.j2"
      dest: "/home/{{ ansible_user }}/odoo/docker-compose.yml"
      mode: "0755"

  - name: "Lancement du docker compose"
    docker-compose:
      project_src: "/home/{{ ansible_user }}/odoo/"
      files:
      - docker-compose.yml
