---
#ansible_python_interpreter: /usr/bin/python3
POSTGRES_DB: postgres
POSTGRES_USER: "{{ postgres_user_vault }}"
POSTGRES_PASSWORD: "{{ odoo_pwd_vault }}"
PG_DATA: odoo-db-data
PG_DATA_FILE: /var/lib/postgresql/data/pgdata
ODOO_PORT: 8069
ODOO_DATA: odoo-web-data
ODOO_WEB_DATA_FILE: /var/lib/odoo
ODOO_CONFIG: ./config:/etc/odoo
ODOO_ADDONS: ./addons:/mnt/extra-addons
NAME_DOCKER_ODOO: docker_odoo
NAME_DOCKER_POSTGRES: docker_postgres
ic_webapp_network: ic_network_webapp
postgres_network: network_postgres
