---
- name: "Installation odoo et postgres"
  hosts: odoo
  become: true
  vars_files:
    - files/secrets/creditentials.yml
  roles:
    - role: docker_role
    - role: odoo_role
- name: "Installation ic_web_app et pg_admin"
  hosts: webapp_pg
  become: true
  vars_files:
    - files/secrets/creditentials.yml
  roles:
    - role: docker_role
    - role: ic-webapp_role
    - role: pgadmin_role