#Create PVC for Odoo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-odoo-claim
  namespace: icgroup
  labels:
    environment : production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi