#Create PV for Odoo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-odoo-volume
  namespace: icgroup
  labels:
    type: local
    environment: production
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/odoo"