---
- name: "Installation chez les dev"
  hosts: odoo
  become: true
  vars_files:
    - files/secrets/creditentials.yml
  roles:
    - role: docker_role
    - role: odoo_role
- name: "Installation chez la prod"
  hosts: webapp_pg
  become: true
  vars_files:
    - files/secrets/creditentials.yml
  roles:
    - role: docker_role
    - role: ic-webapp_role
    - role: pgadmin_role
    
