#deploy Odoo
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: odoo
    environment: production
  name: odoo
  namespace: icgroup
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: odoo
      tier: frontend
  strategy: {}
  template: 
    metadata: 
      labels: 
        app: odoo
        environment: production
        tier: frontend
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 101:101 /var/lib/odoo && sleep 15"]
        volumeMounts:
        - name: odoo-persistent-storage
          mountPath: /var/lib/odoo
      containers: 
        - 
          env: 
            - 
              name: HOST
              value: odoo-postgres
            - 
              name: USER
              value: user-odoo
            - 
              name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-pgsql-password
                  key: odoo
          image: "odoo:13"
          name: odoo
          ports: 
            - 
              containerPort: 8069
              name: odoo
          resources: {}
          volumeMounts: 
            - 
              mountPath: /var/lib/odoo
              name: odoo-persistent-storage
      volumes: 
        - 
          name: odoo-persistent-storage
          persistentVolumeClaim: 
            claimName: data-odoo-claim